# Generated by Django 5.2.7 on 2025-10-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten_dem', models.CharField(blank=True, max_length=100, null=True)),
                ('ten', models.CharField(max_length=50)),
                ('nam_sinh', models.PositiveIntegerField()),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10)),
                ('khoa_phong', models.CharField(blank=True, max_length=100, null=True)),
                ('chuc_danh', models.CharField(blank=True, max_length=100, null=True)),
                ('ngay_tiem_cum', models.DateField(blank=True, null=True)),
                ('chieu_cao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('can_nang', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ket_qua_file', models.CharField(blank=True, max_length=200, null=True)),
                ('nhom', models.CharField(blank=True, max_length=20, null=True)),
                ('ket_luan', models.CharField(blank=True, max_length=200, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ten'],
            },
        ),
    ]
