# Generated by Django 5.2.7 on 2025-10-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, help_text='Mỗi nhân viên có một mã duy nhất (ví dụ: NV001)', max_length=50, null=True, unique=True, verbose_name='Mã nhân viên')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm sinh')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=3, verbose_name='Giới tính')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức danh nghề nghiệp')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức vụ')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Khoa/Phòng')),
                ('vaccinated_flu', models.BooleanField(default=False, verbose_name='Tiêm chủng (Vacxin Cúm)')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Ngày khám')),
                ('exam_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại khám')),
                ('clinic_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cơ sở khám')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Chiều cao (cm)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cân nặng (kg)')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True, verbose_name='Huyết áp (mmHg)')),
                ('health_classification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phân loại sức khỏe')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Kết luận')),
            ],
            options={
                'verbose_name': 'Hồ sơ sức khỏe nhân viên',
                'verbose_name_plural': 'Hồ sơ sức khỏe nhân viên',
                'ordering': ['employee_code'],
            },
        ),
    ]
