# Generated by Django 5.2.7 on 2025-10-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='vaccinated_flu',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='vaccinated_influvac',
            field=models.BooleanField(default=False, verbose_name='Influvac tetra 0.5ml/ Hà Lan'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='vaccinated_vaxigrip',
            field=models.BooleanField(default=False, verbose_name='Vaxigrip tetra 0.5ml/ Pháp'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='vaccination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày tiêm'),
        ),
    ]
