# Generated by Django 5.2.7 on 2025-10-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0002_remove_healthrecord_vaccinated_flu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
