# Generated by Django 5.2.7 on 2025-10-17 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0003_healthrecord_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên khoa/phòng')),
            ],
            options={
                'verbose_name': 'Khoa/Phòng',
                'verbose_name_plural': 'Khoa/Phòng',
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Loại khám')),
            ],
            options={
                'verbose_name': 'Loại khám',
                'verbose_name_plural': 'Loại khám',
            },
        ),
        migrations.CreateModel(
            name='HealthClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Phân loại')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Phân loại sức khoẻ',
                'verbose_name_plural': 'Phân loại sức khoẻ',
            },
        ),
        migrations.AlterModelOptions(
            name='healthrecord',
            options={'ordering': ['-year', 'full_name'], 'verbose_name': 'Hồ sơ khám sức khoẻ', 'verbose_name_plural': 'Hồ sơ khám sức khoẻ'},
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='clinic_name',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='employee_code',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='position',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='vaccinated_influvac',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='vaccinated_vaxigrip',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='vaccination_date',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='ma_nv',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã NV'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='gender',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Năm khám'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_records.department', verbose_name='Khoa/Phòng'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='exam_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_records.examtype', verbose_name='Loại khám'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='health_classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_records.healthclassification', verbose_name='Phân loại sức khoẻ'),
        ),
    ]
