# Generated by Django 5.2.7 on 2025-10-17 03:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0004_department_examtype_healthclassification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm sinh'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Huyết áp (mmHg)'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cơ sở khám'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='conclusion_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kết luận (ghi tay, nếu có)'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Tạo lúc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nhóm'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Chiều cao (cm)'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chức danh nghề nghiệp'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chức vụ'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='health_results/', verbose_name='File kết quả (PDF)'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='stt',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='STT'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='vaccinated_influvac',
            field=models.BooleanField(default=False, verbose_name='Influvac tetra 0.5ml/ Hà Lan'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='vaccinated_vaxigrip',
            field=models.BooleanField(default=False, verbose_name='Vaxigrip tetra 0.5ml/ Pháp'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='vaccination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày tiêm'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Cân nặng (kg)'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_records.department', verbose_name='Khoa/Phòng'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_records.examtype', verbose_name='Loại khám'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='gender',
            field=models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10, null=True, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='health_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_records.healthclassification', verbose_name='Phân loại sức khỏe'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='ma_nv',
            field=models.CharField(blank=True, help_text='Mã nhân viên, không bắt buộc phải unique để lưu nhiều năm', max_length=50, null=True, verbose_name='Mã NV'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='year',
            field=models.PositiveIntegerField(help_text='Năm ghi nhận kết quả (ví dụ 2023)', verbose_name='Năm khám'),
        ),
    ]
