# Generated by Django 5.2.7 on 2025-10-17 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0005_healthrecord_birth_year_healthrecord_blood_pressure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='birth_date',
        ),
    ]
