# Generated by Django 5.2.7 on 2025-10-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0006_remove_healthrecord_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='stt',
        ),
    ]
