# Generated by Django 5.2.7 on 2025-10-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0007_remove_healthrecord_stt'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthclassification',
            name='code',
            field=models.CharField(default=1, max_length=10, verbose_name='Mã loại'),
            preserve_default=False,
        ),
    ]
