# Generated by Django 5.2.7 on 2025-10-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0008_healthclassification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthclassification',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Mã loại'),
        ),
    ]
