# Generated by Django 5.2.7 on 2025-10-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0009_alter_healthclassification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='status',
            field=models.CharField(choices=[('done', 'Đã khám'), ('pending', 'Chưa khám')], default='pending', max_length=20),
        ),
    ]
