# Generated by Django 5.2.7 on 2025-10-24 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0010_healthrecord_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamType',
            new_name='ExaminationType',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Khoa/Phòng', 'verbose_name_plural': 'Danh mục Khoa/Phòng'},
        ),
        migrations.AlterModelOptions(
            name='examinationtype',
            options={'ordering': ['name'], 'verbose_name': 'Loại khám', 'verbose_name_plural': 'Danh mục Loại khám'},
        ),
        migrations.AlterModelOptions(
            name='healthclassification',
            options={'ordering': ['name'], 'verbose_name': 'Phân loại sức khỏe', 'verbose_name_plural': 'Danh mục Phân loại sức khỏe'},
        ),
        migrations.AlterModelOptions(
            name='healthrecord',
            options={'ordering': ['-year', 'employee__full_name'], 'verbose_name': 'Hồ sơ sức khỏe', 'verbose_name_plural': 'Hồ sơ sức khỏe'},
        ),
        migrations.RenameField(
            model_name='healthrecord',
            old_name='exam_type',
            new_name='examination_type',
        ),
        migrations.RemoveField(
            model_name='healthclassification',
            name='code',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='vaccinated',
            field=models.BooleanField(default=False, verbose_name='Đã tiêm vắc-xin'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='vaccine_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên vắc-xin (nếu có)'),
        ),
        migrations.AlterField(
            model_name='healthclassification',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='healthclassification',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Phân loại (I, II, III, IV...)'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='status',
            field=models.CharField(choices=[('done', 'Đã khám'), ('pending', 'Chưa khám')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='vaccination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày tiêm (nếu có)'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Năm hồ sơ'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã nhân viên')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm sinh')),
                ('gender', models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10, null=True, verbose_name='Giới tính')),
                ('job_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chức danh nghề nghiệp')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chức vụ')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_records.department', verbose_name='Khoa/Phòng')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Danh sách nhân viên',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health_records.employee', verbose_name='Nhân viên'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='healthrecord',
            unique_together={('employee', 'year')},
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='department',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='ma_nv',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='position',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='vaccinated_influvac',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='vaccinated_vaxigrip',
        ),
    ]
