# Generated by Django 5.2.7 on 2025-11-01 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0011_rename_examtype_examinationtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=50, verbose_name='Mã batch')),
                ('code', models.CharField(max_length=50, verbose_name='Mã nhân viên')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm sinh')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Giới tính')),
                ('job_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chức danh nghề nghiệp')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chức vụ')),
                ('department_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên khoa/phòng')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Hợp lệ')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Lỗi (nếu có)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Dữ liệu tạm nhân viên',
                'verbose_name_plural': 'Dữ liệu tạm nhân viên',
                'ordering': ['full_name'],
            },
        ),
    ]
