# Generated by Django 5.2.7 on 2025-11-30 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0012_employeetemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecordTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=50, verbose_name='Mã batch')),
                ('employee_code', models.CharField(max_length=50, verbose_name='Mã nhân viên')),
                ('employee_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Họ và tên (nếu có trong file)')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm khám')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Ngày khám')),
                ('examination_type_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Loại khám (text)')),
                ('clinic_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cơ sở khám')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=50, null=True)),
                ('health_classification_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phân loại (text)')),
                ('conclusion_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kết luận nhập tay')),
                ('vaccinated', models.BooleanField(default=False)),
                ('vaccine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vaccination_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True, verbose_name='Hợp lệ')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Lỗi (nếu có)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Dữ liệu tạm hồ sơ sức khỏe',
                'verbose_name_plural': 'Dữ liệu tạm hồ sơ sức khỏe',
                'ordering': ['-created_at'],
            },
        ),
    ]
